groups:
- name: alert.rules_1
  rules:
  - alert: InstanceDown-check
    expr: up == 0
    for: 15s
    labels:
     severity: page
    annotations:
     description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 15 seconds.'
     summary: Instance {{ $labels.instance }} down
